#!/usr/bin/env python3
"""Remove generated local workspace artifacts without touching source or fixtures."""

from __future__ import annotations

import argparse
import os
import shutil
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Heavy generated outputs and one-off visual/debug artifacts produced by local
# migration work. Dependency caches and fixtures are intentionally excluded so a
# cleaned checkout can still run the verification gate without reinstalling.
GENERATED_PATHS = (
    "build",
    "local-artifacts",
    "src-tauri/gen",
    "src-tauri/target",
    ".pytest_cache",
    ".DS_Store",
)
GENERATED_DIR_NAMES = {"__pycache__", ".pytest_cache"}
GENERATED_SUFFIXES = {".pyc", ".pyo"}
PRESERVED_PATHS = {
    ".venv",
    "node_modules",
    "src/gui/new_gui/frontend/node_modules",
    "src/api/dashboard/frontend/node_modules",
    "HomeworkHelper.zip",
    ".omx",
    ".omc",
    ".claude",
}


@dataclass(frozen=True)
class CleanupTarget:
    path: Path
    reason: str


def _is_preserved(path: Path, root: Path) -> bool:
    try:
        relative = path.relative_to(root).as_posix()
    except ValueError:
        return True
    return relative in PRESERVED_PATHS or any(relative.startswith(f"{preserved}/") for preserved in PRESERVED_PATHS)


def collect_cleanup_targets(root: Path = ROOT) -> list[CleanupTarget]:
    root = root.resolve()
    targets: dict[Path, CleanupTarget] = {}

    for relative in GENERATED_PATHS:
        path = root / relative
        if path.exists() and not _is_preserved(path, root):
            targets[path] = CleanupTarget(path, "known generated artifact")

    for current_root, dir_names, file_names in os.walk(root):
        current = Path(current_root)
        dir_names[:] = [
            name
            for name in dir_names
            if name != ".git" and not _is_preserved(current / name, root)
        ]
        paths = [current / name for name in dir_names] + [current / name for name in file_names]
        for path in paths:
            if _is_preserved(path, root):
                continue
            if path.is_dir() and path.name in GENERATED_DIR_NAMES:
                targets[path] = CleanupTarget(path, f"generated directory {path.name}")
            elif path.is_file() and path.suffix in GENERATED_SUFFIXES:
                targets[path] = CleanupTarget(path, f"generated bytecode {path.suffix}")
            elif path.is_file() and path.name == ".DS_Store":
                targets[path] = CleanupTarget(path, "macOS Finder metadata")

    ordered = sorted(targets.values(), key=lambda target: (len(target.path.parts), target.path.as_posix()))
    filtered: list[CleanupTarget] = []
    for target in ordered:
        if any(parent.path in target.path.parents for parent in filtered):
            continue
        filtered.append(target)
    return sorted(filtered, key=lambda target: target.path.as_posix())


def clean_workspace(root: Path = ROOT, *, dry_run: bool = False) -> list[CleanupTarget]:
    targets = collect_cleanup_targets(root)
    for target in targets:
        if dry_run:
            continue
        if target.path.is_dir():
            shutil.rmtree(target.path)
        elif target.path.exists():
            target.path.unlink()
    return targets


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean generated local HomeworkHelper artifacts.")
    parser.add_argument("--dry-run", action="store_true", help="List files/directories without deleting them.")
    args = parser.parse_args()

    targets = clean_workspace(ROOT, dry_run=args.dry_run)
    action = "would remove" if args.dry_run else "removed"
    for target in targets:
        print(f"{action}: {target.path.relative_to(ROOT)} # {target.reason}")
    print(f"{action} {len(targets)} generated artifact(s)")


if __name__ == "__main__":
    main()
